version: '3'

services:
  rsyslog:
    image: jumanjiman/rsyslog
  haproxy18:
    image: haproxy:1.8
    volumes:
      - "${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - 10080:8080
  haproxy20:
    image: haproxy:2.0
    volumes:
      - "${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - 20080:8080
  app:
    hostname: app
    build: app
    volumes:
      - "${PWD}/app:/app"
    working_dir: /app
    environment:
      - GIN_MODE=release
      - PORT=8080
    ports:
      - 8080:8080
    command: go run main.go

